tests: add dependency to libapt-pkg-dev
Without this being available in the host or tox env tests would fail at:
...
  building 'apt_pkg' extension
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/python
  x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv ...
  In file included from python/acquire-item.cc:24:
  python/apt_pkgmodule.h:14:10: fatal error: apt-pkg/hashes.h: No such file ...
     14 | #include <apt-pkg/hashes.h>
        |          ^~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  [end of output]
...
ERROR: could not install deps

Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>