sso: raise UserFacingError for UrlErrors
Instead of error logging and returning None, raise an error for cleaner
user output.  By manually triggering this error (by modifying the code
to use an invalid URL), we now get:

$ UA_CONFIG_FILE=uaclient-devel.conf fakeroot ua attach
ERROR: Could not reach URL https://contracts.staging.canonical.com/broken to authenticate