sso: raise UserFacingError for MacaroonFormatErrors
Instead of error logging and returning None, raise an error for cleaner
user output.  We now get:

ERROR: Invalid root macaroon: Must supply serialized macaroon.